#!/usr/bin/perl
use warnings;
use strict;
use lib qw(lib);
use utf8;
use open qw(:utf8 :std);

use vars qw($VERSION $PROGRAM);
$VERSION    = '0.0.4';
$PROGRAM    = 'twatch';

use Getopt::Long;
use Pod::Usage;

use TWatch;
use TWatch::Config;
use TWatch::Plugin;
use TWatch::Message;

################################################################################
# Processing options
################################################################################
my ($help, $verbose, $execute);
GetOptions(
    'help|?'    => \$help,
    'verbose|?' => \$verbose,
    'execute=s' => \$execute,
) or pod2usage(2);
pod2usage(1) if $help;

# Disable output buffering if verbose
$|=1 if $verbose;

config->set(verbose      => $verbose);
config->set(execute      => $execute);
################################################################################
# Execute
################################################################################
notify('Loading');
# Create main programm object
my $twatch = TWatch->new()
    or die "Can`t create Twatch object.";

notify('Start execute projects');
# Execute projects
$twatch->run;

notify('Send notification mail');
# Send notification mail
message->send();

notify('Execute post plugins');
# Execute post plugins
my $plugins = TWatch::Plugin->new(verbose => $verbose)
    or die "Can`t create TWatch::Plugin object.";
$plugins->post( $twatch );

notify('Done');
exit 0;

__END__

=head1 NAME

twatch - watch torrent trackers and automatically download new torrents

=head1 SYNOPSIS

twatch [options]

 Options:
    -v|--verbose            - Verbose output
    -h|--help               - Read this help and exit
    -e|--execute FILENAME   - Run project by it`s FILENAME

=head1 DESCRIPTION

twatch is a simple and flexible watcher torrent trackers, based on regular
expressons. It can download new torrent files and information about them by
customizable filters.

=head1 REQUESTS & BUGS

Roman V. Nikolaev <rshadow@rambler.ru>

=head1 AUTHORS

Copyright (C) 2008 Roman V. Nikolaev <rshadow@rambler.ru>

=head1 LICENSE

This program is free software: you can redistribute  it  and/or  modify  it
under the terms of the GNU General Public License as published by the  Free
Software Foundation, either version 3 of the License, or (at  your  option)
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even  the  implied  warranty  of  MERCHANTABILITY  or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public  License  for
more details.

You should have received a copy of the GNU  General  Public  License  along
with this program.  If not, see <http://www.gnu.org/licenses/>.

=cut