#!/usr/bin/perl
use warnings;
use strict;
use lib qw(lib);
use utf8;
use open qw(:utf8 :std);

use vars qw($VERSION $PROGRAM);
$PROGRAM    = 'twatch-gtk';
$VERSION    = '0.0.1';

use Glib qw(:constants);
use Gnome2;
use Gtk2 qw(-init);

#die "Glib::Object thread safetly failed"
#    unless Glib::Object->set_threadsafe (TRUE);


use TWatchGtk;

# Создание окна
Gnome2::Program->init ($PROGRAM, $VERSION);

# Запустим приложение
TWatchGtk->new;

# Запуск основной очереди сообщений
Gtk2->main;

0;